--- All types needed for `aggro.vimdoc` to work as expected.
---
---@module 'aggro.vimdoc.type'
---

---@class aggro.vimdoc.AutoDocumentationEntry
---    The simple source/destination of "Lua file that we want to auto-create
---    documentation from + the .txt file that we want auto-create to".
---@field source string
---    An absolute path to a Lua file on-disk. e.g. `"/path/to/foo.lua"`.
---@field destination string
---    An absolute path for the auto-created documentation.
---    e.g. `"/out/aggro_vimdoc.txt"`.
