name: Profile Repository
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Profile Repository
      - uses: ./.github/actions/neovim-busted-profiler-gh-action

